### ISSUE TITLE
CMS page with slash at the end of url_key (identifier) creates directories

### ISSUE THREAD

**Issue by pbrouwers** [enanobots/m2-datapatchcreator#13]
![Screenshot from 2024-03-08 14-42-03](https://github.com/enanobots/m2-datapatchcreator/assets/6161384/a880b2bd-b547-4c19-b1df-fa715aac9383)

**Comment by pbrouwers** [comment]
PR: https://github.com/enanobots/m2-datapatchcreator/pull/14

**Comment by qsolutions-pl** [comment]
Merge in https://github.com/enanobots/m2-datapatchcreator/pull/14
