### ISSUE TITLE
Nanobots admin section is too prevalent

### ISSUE THREAD

**Issue by markshust** [enanobots/m2-datapatchcreator#7]
The default section when I click on System > Configuration should be General. Instead, I see the Nanobots section first. This config entry should probably be de-prioritized so it comes at the end of the system config. 

![Screen Shot 2021-10-29 at 12 47 15 PM](https://user-images.githubusercontent.com/437029/139472875-ffab70f7-14bb-4fd2-a444-7fb71fac4806.png)

**Comment by JosephLeedy** [comment]
Personally, I would prefer that it would be under an existing section if there is one that it fits into. I strongly dislike extensions creating new sections as it creates a mess.

**Comment by markshust** [comment]
@JosephLeedy agreed, it can probably all sit under a single section under System > Config > General > Content Management.

**Comment by enanobots** [comment]
This will be added / changed in the next release, in few days from now.

**Comment by enanobots** [comment]
this is now resolved in 1.0.5 version
